/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Account Enriched
         * @description Resolve a GW2 API key to ``(world_id, world_name, world_population)``.
         *
         *     Composes :meth:`AsyncGuildWars2Client.account_get` with
         *     :meth:`AsyncGuildWars2Client.worlds_get` so a single request to
         *     this endpoint fans out to two upstream v2 calls (account + world)
         *     and returns a deterministic triple to the caller.
         */
        get: operations["get_account_enriched_api_v1_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fights
         * @description Return up to ``limit`` fights (skipping the first ``offset``).
         */
        get: operations["list_fights_api_v1_fights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fights/{fight_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fight
         * @description Return a fight by id (the upload's sha256).
         */
        get: operations["get_fight_api_v1_fights__fight_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fights/{fight_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fight Events
         * @description Return the aggregated event stream for one fight.
         *
         *     Phase 7 v1: drained by :meth:`PythonEvtcParser.parse_events`,
         *     persisted to MinIO at ``events/{fight_id}.jsonl.gz``, and surfaced
         *     here as a combined ``FightEventsSummaryOut`` so the frontend
         *     renders the timeline + per-target DPS without two extra round-trips.
         *
         *     Phase 7 v1 of the API (apps/api 0.3.0): the per-target healing
         *     roll-up is added as a sibling field of ``target_dps``, completing
         *     the v2 ``Event`` discriminated union consumption on the HTTP
         *     surface. The route filters the heterogeneous JSONL stream
         *     by ``isinstance`` at the call site and invokes
         *     :class:`gw2_analytics.target_healing.TargetHealingAggregator`
         *     on the same ``duration_s`` used for the damage roll-up.
         *
         *     Response codes:
         *
         *     - ``404 Not Found``: fight id is unknown OR the events blob is
         *       missing (pre-Phase 7 row OR the parser pass yielded zero events
         *       after filtering). ``NULL`` ``events_blob_uri`` is the
         *       ground-truth signal for "no event data available"; we
         *       deliberately do NOT return ``200 OK`` with empty arrays because
         *       that would conflate "parser ran, nothing happened" with "data
         *       unavailable". Re-uploading + reparsing the source ``.zevtc``
         *       re-populates the blob.
         *     - ``422 Unprocessable Entity``: ``window_s`` is outside ``[1, 600]``.
         *       Handled by FastAPI before this handler runs.
         *     - ``502 Bad Gateway``: events blob is present but corrupt (gzip
         *       decompression failure or non-JSON payload). The fight row is
         *       still valid; this is a blob-store consistency issue, not a
         *       client error.
         */
        get: operations["get_fight_events_api_v1_fights__fight_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fights/{fight_id}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fight Skills
         * @description Return the per-skill roll-up for one fight.
         *
         *     v0.7.0 ships this as a SEPARATE endpoint (not folded into
         *     :func:`get_fight_events`); same rationale as
         *     :func:`get_fight_squads`. The route loads the per-fight
         *     ``OrmFightSkill`` rows to build the ``skill_id -> skill_name``
         *     map and invokes
         *     :class:`gw2_analytics.skill_usage.SkillUsageAggregator` on the
         *     split event streams. No ``duration_s`` is passed (the
         *     skill-usage aggregator does not compute per-second rates; see
         *     the module docstring for the rationale).
         */
        get: operations["get_fight_skills_api_v1_fights__fight_id__skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fights/{fight_id}/squads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fight Squads
         * @description Return the per-subgroup (squad) roll-up for one fight.
         *
         *     v0.7.0 ships this as a SEPARATE endpoint (not folded into
         *     :func:`get_fight_events`) so the per-fight drill-down page can
         *     fetch it in parallel with the per-target roll-ups via
         *     ``Promise.all``; folding it into the existing payload would
         *     force the page to refetch the full event blob even when only
         *     the squad view is requested.
         *
         *     The route decompresses the same events blob the per-target
         *     trio uses, splits by ``isinstance`` at the call site, loads
         *     the per-fight agents to build the ``agent_id -> subgroup``
         *     map, and invokes
         *     :class:`gw2_analytics.squad_rollup.SquadRollupAggregator` on
         *     the same ``duration_s``.
         *
         *     Response codes match :func:`get_fight_events` exactly
         *     (``404`` for missing fight / blob / corrupt blob).
         */
        get: operations["get_fight_squads_api_v1_fights__fight_id__squads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fights/{fight_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fight Timeline
         * @description Return the per-fight timeline (damage + healing + buff-removal over time) for one fight.
         *
         *     v0.8.9 ships this as a SEPARATE endpoint (not folded into
         *     :func:`get_fight_events`) so the per-fight drill-down page
         *     can fetch it in parallel with the per-target trio + squads +
         *     skills via ``Promise.allSettled``; folding it into the
         *     existing ``FightEventsSummaryOut`` would force the page to
         *     refetch the full event blob even when only the per-fight
         *     timeline is requested. The route reuses
         *     :func:`_load_fight_events` (the same shared helper the
         *     per-target trio + squads + skills endpoints use) and invokes
         *     :class:`gw2_analytics.per_fight_timeline.PerFightTimelineAggregator`
         *     on the parsed events.
         *
         *     The aggregator's ``agents`` + ``duration_s`` parameters are
         *     accepted for signature parity with the per-target trio +
         *     squads + skills aggregators but NOT consumed by the
         *     per-bucket aggregation (the per-bucket skeleton is
         *     target-agnostic + duration-agnostic). The route passes
         *     ``agents=[]`` + the computed ``duration_s`` (derived from
         *     ``max(event.time_ms) / 1000.0`` to match the contract on
         *     :func:`get_fight_events`).
         *
         *     Response codes match :func:`get_fight_events` exactly:
         *
         *     - ``404 Not Found``: fight id is unknown OR the events
         *       blob is missing (pre-Phase 7 row OR the parser pass
         *       yielded zero events after filtering). ``NULL``
         *       ``events_blob_uri`` is the ground-truth signal for "no
         *       event data available"; we deliberately do NOT return
         *       ``200 OK`` with empty arrays because that would
         *       conflate "parser ran, nothing happened" with "data
         *       unavailable".
         *     - ``422 Unprocessable Entity``: ``window_s`` is outside
         *       ``[1, 600]``. Handled by FastAPI before this handler
         *       runs.
         *     - ``502 Bad Gateway``: events blob is present but
         *       corrupt (gzip decompression failure or non-JSON
         *       payload). The fight row is still valid; this is a
         *       blob-store consistency issue, not a client error.
         */
        get: operations["get_fight_timeline_api_v1_fights__fight_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health Summary
         * @description Return the fight-summary drift for the operational health probe.
         *
         *     Response shape::
         *
         *         {
         *             "total_fights": 100,
         *             "fights_with_summaries": 95,
         *             "drift_count": 5,
         *             "drift_pct": 5.0,
         *             "status": "drift"
         *         }
         *
         *     - ``total_fights``: the total number of ``OrmFight`` rows.
         *     - ``fights_with_summaries``: the number of distinct
         *       ``fight_id`` values that have at least one
         *       ``OrmFightPlayerSummary`` row.
         *     - ``drift_count``: ``total_fights - fights_with_summaries``,
         *       the number of fights whose summary rows are missing.
         *       Zero is the healthy state.
         *     - ``drift_pct``: ``drift_count / total_facts * 100`` as a
         *       float rounded to 2 decimal places, or ``0.0`` on an
         *       empty database.
         *     - ``status``: ``"ok"`` when ``drift_count == 0``,
         *       ``"drift"`` otherwise. The cron integration can
         *       branch on this field without computing its own
         *       threshold.
         *
         *     The probe is a single SQL round-trip with 2 subqueries;
         *     it is safe to poll from a monitoring system at a high
         *     cadence (the query plan uses the ``fights`` PK index
         *     + the ``fight_player_summaries`` PK index).
         */
        get: operations["get_health_summary_api_v1_health_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description Return up to ``limit`` players (skipping the first ``offset``).
         *
         *     The route computes the cross-fight roll-up over ALL fights
         *     (not just the paginated window -- the offset/limit apply to
         *     the final player list, not the underlying fight set), then
         *     applies the offset/limit to the sorted result. This keeps the
         *     response stable across page boundaries: a player who was
         *     page-1 row 5 last request is page-1 row 5 this request (the
         *     cross-fight roll-up is deterministic).
         *
         *     v0.9.0: the optional ``?profession=`` filter is applied
         *     between the cross-fight roll-up + the offset/limit. An
         *     invalid name (or integer) surfaces as 422 via the
         *     :func:`_parse_profession_filter` helper.
         */
        get: operations["list_players_api_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{account_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player
         * @description Return the full profile + per-fight breakdown for one account.
         *
         *     ``account_name`` is the URL-decoded arcdps account name (e.g.
         *     ``:account.1234``). The ``:path`` converter lets the value
         *     contain ``/`` characters that would otherwise terminate the
         *     path match; FastAPI decodes the URL-encoded form before
         *     handing the string to the handler. The route raises
         *     ``404 Not Found`` when no agent in any fight carries the
         *     requested ``account_name``.
         *
         *     The per-fight breakdown is built by filtering the
         *     cross-fight roll-up to ``account_name`` and emitting one
         *     :class:`PerFightBreakdownRowOut` per attended fight, sorted
         *     by ``started_at`` DESC.
         */
        get: operations["get_player_api_v1_players__account_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{account_name}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Timeline
         * @description Return the per-fight historical timeline for one account.
         *
         *     v0.8.0 of the API: the analyst-facing timeline chart on the
         *     profile page. Reuses :func:`_compute_contributions` (the same
         *     inner loop the list + detail endpoints use) so the route
         *     joins + decompresses the events blobs once per request and
         *     paginates in-memory.
         *
         *     Sort order is **recency-first** (``started_at DESC``, with
         *     ``fight_id ASC`` as the tiebreaker for fights that share a
         *     timestamp) -- the analyst scans a per-account trend, so the
         *     most recent fight lands in the top-left slot of the chart.
         *     The tiebreaker is the canonical deterministic-ordering
         *     contract from the cross-fight roll-up.
         *
         *     ``limit`` is clamped to ``[1, 100]``; ``offset`` is clamped
         *     to ``[0, inf)``. Out-of-range values raise ``422`` via
         *     FastAPI's ``Query`` validation (BEFORE the handler runs,
         *     so the route never sees a bad value).
         *
         *     The route raises ``404 Not Found`` when no agent in any
         *     fight carries the requested ``account_name`` -- mirrors the
         *     detail endpoint's contract.
         *
         *     Declaration order matters
         *     -------------------------
         *     This route MUST be declared BEFORE
         *     ``get_player`` (the catch-all ``{account_name:path}`` route).
         *     FastAPI matches routes in declaration order; if the catch-all
         *     is declared first, ``/{account_name:path}`` would greedily
         *     match ``/TestAccount.1234/timeline`` with
         *     ``account_name="TestAccount.1234/timeline"`` and return 404
         *     before the timeline route ever fires. The current declaration
         *     order (list + timeline + detail) is the canonical
         *     "more-specific-first" pattern.
         *
         *     v0.8.4 perf note
         *     ----------------
         *     v0.8.0 of the route did the per-fight roll-up in-memory on
         *     every request. v0.8.4 materialises the per-(fight, account)
         *     totals in ``OrmFightPlayerSummary`` (populated by the
         *     background parser) so the fast-path serves the timeline
         *     from a single indexed PK lookup per fight. The slow-path
         *     fallback (the original v0.7.0 blob walk) covers pre-migration
         *     fights transparently. Per-request latency drops from 5-30s
         *     to a few milliseconds for users with 100+ fights.
         */
        get: operations["get_player_timeline_api_v1_players__account_name__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Upload
         * @description Accept a ``.zevtc`` upload.
         */
        post: operations["create_upload_api_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upload */
        get: operations["get_upload_api_v1_uploads__upload_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Webhooks
         * @description List active (non-revoked) webhook subscriptions. Secrets never returned.
         */
        get: operations["list_webhooks_api_v1_webhooks_get"];
        put?: never;
        /**
         * Create Webhook
         * @description Register a webhook subscription (returns secret ONE time).
         */
        post: operations["create_webhook_api_v1_webhooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/dlq/{delivery_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay Dlq Delivery
         * @description Replay one DLQ entry: create a fresh delivery + delete the
         *     DLQ row atomically. ``delivery_id`` is the original DLQ
         *     entry's id (NOT a generation round -- the original id is
         *     retained in the dlq row).
         *
         *     404 cases (the only failure paths):
         *
         *     1. DLQ entry not found (the id is unknown).
         *     2. Original subscription missing OR revoked -- the DLQ row
         *        retains the original ``subscription_id``, but if the
         *        subscription is gone (hard-delete) or revoked
         *        (soft-delete via the v0.9.0 endpoint), replaying is unsafe
         *        (no HMAC secret + no URL).
         *     3. Original upload missing (hard-deleted between the parse+DLQ
         *        and the replay) -- defensive; the payload still references
         *        the upload's fight summary but a 404 here surfaces the
         *        orphaned-row case.
         */
        post: operations["replay_dlq_delivery_api_v1_webhooks_dlq__delivery_id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Webhook
         * @description Look up one subscription by id (404 if revoked or missing).
         */
        get: operations["get_webhook_api_v1_webhooks__subscription_id__get"];
        put?: never;
        post?: never;
        /**
         * Revoke Webhook
         * @description Idempotent soft-delete (sets revoked_at). Already-revoked returns 204.
         */
        delete: operations["revoke_webhook_api_v1_webhooks__subscription_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountEnrichedOut
         * @description GET /api/v1/account response.
         *
         *     Composed in :mod:`gw2analytics_api.routes.account` from two
         *     upstream calls (``AsyncGuildWars2Client.account_get`` +
         *     ``worlds_get([account.world_id])``) so the client gets a single
         *     (world_id, world_name, world_population) tuple per GW2 API key.
         *
         *     ``world_population`` is the canonical capitalised ``Population``
         *     string exactly as the v2 API emits (``"Low" | "Medium" | "High" |
         *     "VeryHigh" | "Full"``). Forward-compat is delegated to ``gw2_core``
         *     ``Population`` parsing; if the v2 API grows a new bucket, the
         *     underlying ``WorldInfo`` validation raises and the route surfaces
         *     a 502 rather than silently coercing to a known bucket.
         */
        AccountEnrichedOut: {
            /** World Id */
            world_id: number;
            /** World Name */
            world_name: string;
            /** World Population */
            world_population: string;
        };
        /** AgentOut */
        AgentOut: {
            /** Account Name */
            account_name?: string | null;
            /** Agent Id */
            agent_id: number;
            /** Elite Spec */
            elite_spec: string;
            /** Is Player */
            is_player: boolean;
            /** Name */
            name: string;
            /** Profession */
            profession: string;
            /** Subgroup */
            subgroup?: string | null;
        };
        /** Body_create_upload_api_v1_uploads_post */
        Body_create_upload_api_v1_uploads_post: {
            /**
             * File
             * @description A .zevtc combat log file
             */
            file: string;
        };
        /**
         * EventBucketOut
         * @description Response schema for ``GET /api/v1/fights/{fight_id}/events``.
         *
         *     Mirrors :class:`gw2_analytics.event_window.EventBucket` so the
         *     OpenAPI shape is locked before the parser-side integration in
         *     Phase 6 v2. Phase 6 v1 returns an empty list — this schema is
         *     future-proofed for the moment parsing of events arrives.
         */
        EventBucketOut: {
            /**
             * Damage Total
             * @default 0
             */
            damage_total: number;
            /** End Ms */
            end_ms: number;
            /**
             * Event Count
             * @default 0
             */
            event_count: number;
            /**
             * Healing Total
             * @default 0
             */
            healing_total: number;
            /** Start Ms */
            start_ms: number;
        };
        /**
         * FightEventsSummaryOut
         * @description Combined aggregation payload returned by ``GET /api/v1/fights/{fight_id}/events``.
         *
         *     Phase 7 v1 ships a single bound response so the frontend can render
         *     the timeline + per-target DPS without two extra round-trips.
         *     Phase 7 v1 of the API adds the per-target healing roll-up as a
         *     sibling field, completing the v2 Event union consumption on the
         *     HTTP surface (the v2 ``Event`` discriminated union
         *     ``DamageEvent | HealingEvent`` is now materialised as both a
         *     per-target DPS roll-up AND a per-target healing roll-up in a
         *     single round-trip).
         *
         *     Contract:
         *
         *     - ``duration_s`` is computed natively from
         *       ``max(event.time_ms) / 1000.0`` because the V1.3 EVTC header
         *       does not carry a wall-clock duration scalar.
         *     - ``target_dps`` is empty when the parser yielded zero damage events
         *       (after the ``is_statechange == 0`` ``/`` ``is_nondamage == 0``
         *       ``/`` ``value > 0`` filter); the route returns ``404 Not Found``
         *       when the events blob is missing entirely (pre-Phase-7 row OR the
         *       blob upload failed).
         *     - ``target_healing`` is the strict parallel of ``target_dps``
         *       (filtered by ``isinstance(e, HealingEvent)`` and rolled up via
         *       :class:`gw2_analytics.target_healing.TargetHealingAggregator`).
         *       Empty when the parser yielded zero healing events; the
         *       damage-only / heal-only / mixed-fight cases all surface
         *       correctly because the route filters at the call site rather
         *       than branching inside the aggregator.
         *     - ``target_buff_removal`` (Phase 8) is the third sibling roll-up,
         *       filtered by ``isinstance(e, BuffRemovalEvent)`` and rolled up via
         *       :class:`gw2_analytics.target_buff_removal.TargetBuffRemovalAggregator`.
         *       The parser yields ``BuffRemovalEvent`` from two distinct paths:
         *       (a) a single ``cbtevent`` record with ``is_statechange == 0``,
         *       ``is_nondamage > 0``, ``value > 0``, ``buff_dmg > 0`` yields
         *       BOTH a ``HealingEvent`` AND a ``BuffRemovalEvent`` (corrupting
         *       / confusion skills that heal the caster + strip a boon); (b) a
         *       record with ``is_nondamage > 0``, ``value == 0``,
         *       ``buff_dmg > 0`` yields ONLY a ``BuffRemovalEvent`` (pure
         *       strip). Empty when the parser yielded zero strip events.
         *     - ``event_windows`` is empty when there are no events. The
         *       ``EventWindowAggregator`` accepts the full ``Iterable[Event]``
         *       and accounts damage + healing in one bucket
         *       (``damage_total`` + ``healing_total`` + ``event_count``).
         *       Phase 8 deliberately does NOT extend ``EventBucketOut`` with a
         *       ``buff_removal_total`` field -- the per-bucket window contract
         *       is locked and the heterogeneous stream passes through unchanged
         *       (the aggregator's unknown-event fallback increases
         *       ``event_count``).
         */
        FightEventsSummaryOut: {
            /** Duration S */
            duration_s: number;
            /**
             * Event Windows
             * @default []
             */
            event_windows: components["schemas"]["EventBucketOut"][];
            /** Fight Id */
            fight_id: string;
            /**
             * Target Buff Removal
             * @default []
             */
            target_buff_removal: components["schemas"]["TargetBuffRemovalRowOut"][];
            /**
             * Target Dps
             * @default []
             */
            target_dps: components["schemas"]["TargetDpsRowOut"][];
            /**
             * Target Healing
             * @default []
             */
            target_healing: components["schemas"]["TargetHealingRowOut"][];
        };
        /** FightOut */
        FightOut: {
            /** Agent Count */
            agent_count: number;
            /**
             * Agents
             * @default []
             */
            agents: components["schemas"]["AgentOut"][];
            /** Build Version */
            build_version: string;
            /** Encounter Id */
            encounter_id: number;
            /** Game Type */
            game_type: number;
            /** Id */
            id: string;
            /**
             * Skills
             * @default []
             */
            skills: components["schemas"]["SkillOut"][];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /**
         * FightSkillsOut
         * @description Combined payload from ``GET /api/v1/fights/{fight_id}/skills``.
         *
         *     v0.7.0 ships the skill-usage roll-up as a separate endpoint
         *     (not folded into :class:`FightEventsSummaryOut`); same
         *     rationale as :class:`FightSquadsOut`. The route loads the
         *     fight's ``OrmFightSkill`` rows to build the
         *     ``skill_id -> skill_name`` map and invokes
         *     :class:`gw2_analytics.skill_usage.SkillUsageAggregator` on
         *     the split event streams.
         */
        FightSkillsOut: {
            /** Fight Id */
            fight_id: string;
            /**
             * Skills
             * @default []
             */
            skills: components["schemas"]["SkillUsageRowOut"][];
        };
        /**
         * FightSquadsOut
         * @description Combined payload from ``GET /api/v1/fights/{fight_id}/squads``.
         *
         *     v0.7.0 ships the squad-rollup as a separate endpoint (not
         *     folded into :class:`FightEventsSummaryOut`) so the per-fight
         *     drill-down page can fetch it in parallel with the per-target
         *     roll-ups via ``Promise.all``; folding it into the existing
         *     payload would force the page to refetch the full event blob
         *     even when only the squad view is requested. The route
         *     decompresses the same events blob, splits by ``isinstance``,
         *     and invokes
         *     :class:`gw2_analytics.squad_rollup.SquadRollupAggregator` on
         *     the same ``duration_s`` used by the per-target trio.
         */
        FightSquadsOut: {
            /** Duration S */
            duration_s: number;
            /** Fight Id */
            fight_id: string;
            /**
             * Squads
             * @default []
             */
            squads: components["schemas"]["SquadRollupRowOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PerFightBreakdownRowOut
         * @description One row of the per-fight breakdown on :class:`PlayerProfileOut`.
         *
         *     The route computes one of these per ``(fight_id, account_name)``
         *     pair by walking the fight's events blob and accumulating
         *     magnitudes where ``event.source_agent_id`` maps to
         *     ``account_name`` via :class:`OrmFightAgent`.
         */
        PerFightBreakdownRowOut: {
            /** Fight Id */
            fight_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Total Buff Removal */
            total_buff_removal: number;
            /** Total Damage */
            total_damage: number;
            /** Total Healing */
            total_healing: number;
        };
        /**
         * PerFightTimelineOut
         * @description Response from ``GET /api/v1/fights/{fight_id}/timeline``.
         *
         *     v0.8.9 ships this as a SEPARATE endpoint (not folded into
         *     :class:`FightEventsSummaryOut`) for the same reason the
         *     squads + skills endpoints are separate: a single bound
         *     response would force the page to refetch the full event
         *     blob even when only the per-fight timeline is requested.
         *     The route reuses :func:`_load_fight_events` (the same
         *     shared helper the per-target trio + squads + skills
         *     endpoints use) and invokes
         *     :class:`gw2_analytics.per_fight_timeline.PerFightTimelineAggregator`
         *     on the parsed events.
         *
         *     - ``fight_id`` echoes the path param so the wire consumer
         *       can verify which fight the timeline belongs to.
         *     - ``window_s`` echoes the query param so the consumer can
         *       verify the bucket size the route applied (matches the
         *       ``window_s`` contract on :func:`get_fight_events`).
         *     - ``duration_s`` mirrors the same scalar on
         *       :class:`FightEventsSummaryOut` (computed natively as
         *       ``max(event.time_ms) / 1000.0`` because the V1.3 EVTC
         *       header does not carry a wall-clock duration).
         *     - ``points`` is the list of :class:`PerFightTimelinePointOut`
         *       rows, sorted ascending by ``window_start_ms``. Empty
         *       when the parser yielded zero events (a defensive empty
         *       list -- the per-fight timeline is the "what happened
         *       in this fight" use case, and a 0-event fight has no
         *       timeline to show).
         */
        PerFightTimelineOut: {
            /** Duration S */
            duration_s: number;
            /** Fight Id */
            fight_id: string;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["PerFightTimelinePointOut"][];
            /** Window S */
            window_s: number;
        };
        /**
         * PerFightTimelinePointOut
         * @description One row of the per-fight timeline on :class:`PerFightTimelineOut`.
         *
         *     v0.8.9 ships this lean schema for the new per-fight timeline
         *     chart: ``window_start_ms`` + ``window_end_ms`` (the
         *     half-open ``[start, end)`` range) + the 3 totals. The chart
         *     consumes only the 3 totals per bucket (no rate columns, no
         *     per-target roll-ups). Mirrors the wire shape of
         *     :class:`EventBucketOut` (the per-bucket row on the existing
         *     ``/events`` endpoint) but with ``window_start_ms`` /
         *     ``window_end_ms`` instead of ``start_ms`` / ``end_ms`` so the
         *     two endpoints' row shapes are visually distinct (the
         *     per-fight timeline is its own wire surface, not a folded-in
         *     extension of the events payload).
         */
        PerFightTimelinePointOut: {
            /** Total Buff Removal */
            total_buff_removal: number;
            /** Total Damage */
            total_damage: number;
            /** Total Healing */
            total_healing: number;
            /** Window End Ms */
            window_end_ms: number;
            /** Window Start Ms */
            window_start_ms: number;
        };
        /**
         * PlayerListRowOut
         * @description One row of the cross-fight player roll-up returned by ``GET /api/v1/players``.
         *
         *     Lean schema for the list endpoint: the analyst scans a
         *     paginated AG Grid of accounts. The full per-fight breakdown
         *     lives on :class:`PlayerProfileOut` (returned by the detail
         *     endpoint).
         *
         *     ``account_name`` is the operational identity (stable across
         *     uploads). ``name`` is the last-seen char-name (cosmetic
         *     identity). The three totals are summed across every fight the
         *     account attended.
         */
        PlayerListRowOut: {
            /** Account Name */
            account_name: string;
            /** Elite Spec */
            elite_spec: string;
            /** Fights Attended */
            fights_attended: number;
            /** Name */
            name: string;
            /** Profession */
            profession: string;
            /** Total Buff Removal */
            total_buff_removal: number;
            /** Total Damage */
            total_damage: number;
            /** Total Healing */
            total_healing: number;
        };
        /**
         * PlayerProfileOut
         * @description Full player profile returned by ``GET /api/v1/players/{account_name}``.
         *
         *     Mirrors :class:`gw2_analytics.player_profile.PlayerProfile`
         *     with the addition of the per-fight breakdown array
         *     (``per_fight_breakdown``) and the ``started_at`` timestamps
         *     on each fight row. v0.7.0 ships the player-centric view of
         *     the dataset; the route joins on ``OrmFightAgent.account_name``
         *     to build the cross-fight roll-up.
         *
         *     ``account_name`` is URL-encoded in the request path because
         *     arcdps prefixes the value with ``:`` (e.g. ``:account.1234``);
         *     FastAPI's path-parameter parser handles the decoding. The
         *     route raises ``404 Not Found`` when no agent in any fight
         *     carries the requested ``account_name``.
         */
        PlayerProfileOut: {
            /** Account Name */
            account_name: string;
            /**
             * Attended Fight Ids
             * @default []
             */
            attended_fight_ids: string[];
            /** Elite Spec */
            elite_spec: string;
            /** Fights Attended */
            fights_attended: number;
            /** Name */
            name: string;
            /**
             * Per Fight Breakdown
             * @default []
             */
            per_fight_breakdown: components["schemas"]["PerFightBreakdownRowOut"][];
            /** Profession */
            profession: string;
            /** Total Buff Removal */
            total_buff_removal: number;
            /** Total Damage */
            total_damage: number;
            /** Total Healing */
            total_healing: number;
        };
        /**
         * PlayerTimelineOut
         * @description Response from ``GET /api/v1/players/{account_name}/timeline``.
         *
         *     The ``total`` field is the un-paginated count of attended
         *     fights (the same scalar as :attr:`PlayerProfileOut.fights_attended`).
         *     The client uses ``total`` to decide whether the "Load more"
         *     button should render (``points.length < total`` means there
         *     are more fights to fetch). The ``limit`` + ``offset`` echo
         *     the request params so the client can compute the next-page
         *     URL without a separate round-trip.
         *
         *     v0.8.0 of the API surfaces the timeline as a separate
         *     endpoint (not folded into :class:`PlayerProfileOut`) so the
         *     profile page can fetch the first page in parallel with the
         *     profile + per-fight breakdown via ``Promise.allSettled`` --
         *     a single bound response would force the page to refetch the
         *     full per-fight breakdown just to learn ``total``.
         *
         *     v0.8.1 of the API: the ``bucket`` field exposes the per-fight
         *     (``"fight"``, default) vs per-day (``"day"``) grouping
         *     contract. ``"day"`` collapses all fights sharing a calendar
         *     day into one point whose ``total_damage`` / ``total_healing``
         *     / ``total_buff_removal`` are the SUM of the day's fights.
         *     The ``started_at`` of a day-bucketed point is the day's
         *     midnight (UTC) so the chart's X-axis can detect the
         *     day-aligned timestamps and render ``MM/DD`` instead of
         *     ``MM/DD HH:MM``. The ``fight_id`` of a day-bucketed point
         *     is the most-recent fight_id of the day (the deterministic
         *     tiebreaker; the chart keys on ``fight_id`` so the React
         *     reconciler is happy).
         */
        PlayerTimelineOut: {
            /** Account Name */
            account_name: string;
            /**
             * Bucket
             * @default fight
             * @enum {string}
             */
            bucket: "fight" | "day";
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["PlayerTimelinePointOut"][];
            /** Total */
            total: number;
            /**
             * Tz
             * @default UTC
             */
            tz: string;
        };
        /**
         * PlayerTimelinePointOut
         * @description One row of the per-fight historical timeline on :class:`PlayerTimelineOut`.
         *
         *     Strict parallel of :class:`PerFightBreakdownRowOut` (the per-fight
         *     breakdown on the profile page): ``fight_id`` + ``started_at`` +
         *     the 3 totals. v0.8.0 ships this lean schema for the timeline
         *     chart -- the analyst UI consumes only the 3 totals per fight
         *     (no rate columns, no per-target roll-ups).
         */
        PlayerTimelinePointOut: {
            /** Fight Id */
            fight_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Total Buff Removal */
            total_buff_removal: number;
            /** Total Damage */
            total_damage: number;
            /** Total Healing */
            total_healing: number;
        };
        /** SkillOut */
        SkillOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * SkillUsageRowOut
         * @description One per-skill roll-up row in :class:`FightSkillsOut`.
         *
         *     Mirrors :class:`gw2_analytics.skill_usage.SkillUsageRow`; the
         *     ``hit_count`` field is kept on the API surface (it's the
         *     per-skill event frequency, the only per-skill signal that
         *     doesn't depend on a duration). v0.7.0 ships this fifth
         *     roll-up.
         */
        SkillUsageRowOut: {
            /** Hit Count */
            hit_count: number;
            /** Skill Id */
            skill_id: number;
            /** Skill Name */
            skill_name: string;
            /** Total Buff Removal */
            total_buff_removal: number;
            /** Total Damage */
            total_damage: number;
            /** Total Healing */
            total_healing: number;
        };
        /**
         * SquadRollupRowOut
         * @description One per-subgroup roll-up row in :class:`FightSquadsOut`.
         *
         *     Mirrors :class:`gw2_analytics.squad_rollup.SquadRollupRow` with
         *     the ``hit_count`` field dropped from the API surface
         *     (analyst-only signal; UI shows ``total_damage`` +
         *     ``total_healing`` + ``total_buff_removal`` + the three
         *     per-second rates only). v0.7.0 ships this fourth roll-up,
         *     source-side (the subgroup is the actor's, not the target's).
         */
        SquadRollupRowOut: {
            /** Bps */
            bps: number;
            /** Dps */
            dps: number;
            /** Hps */
            hps: number;
            /** Subgroup */
            subgroup: string;
            /** Total Buff Removal */
            total_buff_removal: number;
            /** Total Damage */
            total_damage: number;
            /** Total Healing */
            total_healing: number;
        };
        /**
         * SummaryDrift
         * @description The shape of the ``GET /api/v1/health/summary`` response.
         *
         *     Attributes
         *     ----------
         *     total_fights:
         *         The total number of ``OrmFight`` rows in the database.
         *     fights_with_summaries:
         *         The number of distinct ``fight_id`` values that have
         *         at least one ``OrmFightPlayerSummary`` row. The
         *         ``DISTINCT`` is necessary because a single fight can
         *         have multiple summary rows (one per
         *         ``(fight_id, account_name)`` pair).
         *     drift_count:
         *         ``total_fights - fights_with_summaries`` -- the number
         *         of fights whose summary rows are missing.
         *     drift_pct:
         *         ``drift_count / total_fights * 100`` as a float, or
         *         ``0.0`` if ``total_fights == 0`` (avoids a
         *         ``ZeroDivisionError`` on an empty database). The
         *         ``round(..., 2)`` keeps the response small + stable
         *         for monitoring diffs.
         *     status:
         *         The qualitative health state. ``"ok"`` when
         *         ``drift_count == 0`` (no missing summary rows) and
         *         ``"drift"`` otherwise. The cron integration can
         *         branch on this field instead of computing its own
         *         threshold from the raw numbers.
         */
        SummaryDrift: {
            /** Drift Count */
            drift_count: number;
            /** Drift Pct */
            drift_pct: number;
            /** Fights With Summaries */
            fights_with_summaries: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "drift";
            /** Total Fights */
            total_fights: number;
        };
        /**
         * TargetBuffRemovalRowOut
         * @description One buff-removal roll-up row in :class:`FightEventsSummaryOut`.
         *
         *     Mirrors
         *     :class:`gw2_analytics.target_buff_removal.TargetBuffRemovalRow`
         *     with the ``strip_count`` field dropped from the API surface
         *     (analyst-only signal; UI shows ``total_buff_removal`` + ``bps``
         *     only). Strict parallel of :class:`TargetDpsRowOut` /
         *     :class:`TargetHealingRowOut` so the trio reads as one design.
         *     Phase 8 ships this third roll-up.
         *
         *     v0.8.3 of the API: optional ``name`` field, strict parallel of
         *     :attr:`TargetDpsRowOut.name`. See that field for the contract.
         */
        TargetBuffRemovalRowOut: {
            /** Bps */
            bps: number;
            /** Name */
            name?: string | null;
            /** Target Agent Id */
            target_agent_id: number;
            /** Total Buff Removal */
            total_buff_removal: number;
        };
        /**
         * TargetDpsRowOut
         * @description One damage roll-up row in :class:`FightEventsSummaryOut`.
         *
         *     Mirrors :class:`gw2_analytics.target_dps.TargetDpsRow` with the
         *     ``attack_count`` field dropped from the API surface (analyst-only
         *     signal; UI shows ``total_damage`` + ``dps`` only).
         *
         *     v0.8.3 of the API: the optional ``name`` field surfaces the
         *     player-name denormalisation passed to the aggregator's
         *     ``name_map`` parameter. ``None`` (serialised as ``null``) when
         *     the agent id has no registered char-name (an NPC) or when the
         *     route did not pass a ``name_map``; the frontend falls back to
         *     the raw ``target_agent_id`` in that case. The field is additive
         *     -- existing wire consumers ignore it.
         */
        TargetDpsRowOut: {
            /** Dps */
            dps: number;
            /** Name */
            name?: string | null;
            /** Target Agent Id */
            target_agent_id: number;
            /** Total Damage */
            total_damage: number;
        };
        /**
         * TargetHealingRowOut
         * @description One healing roll-up row in :class:`FightEventsSummaryOut`.
         *
         *     Mirrors :class:`gw2_analytics.target_healing.TargetHealingRow`
         *     with the ``heal_count`` field dropped from the API surface
         *     (analyst-only signal; UI shows ``total_healing`` + ``hps`` only).
         *     Strict parallel of :class:`TargetDpsRowOut` so the pair reads as
         *     one design.
         *
         *     v0.8.3 of the API: optional ``name`` field, strict parallel of
         *     :attr:`TargetDpsRowOut.name`. See that field for the contract.
         */
        TargetHealingRowOut: {
            /** Hps */
            hps: number;
            /** Name */
            name?: string | null;
            /** Target Agent Id */
            target_agent_id: number;
            /** Total Healing */
            total_healing: number;
        };
        /**
         * UploadCreatedResponse
         * @description Returned from POST /uploads before parsing is finalised.
         */
        UploadCreatedResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sha256 */
            sha256: string;
            /** Status */
            status: string;
        };
        /** UploadOut */
        UploadOut: {
            /** Error Message */
            error_message?: string | null;
            /** Fight Id */
            fight_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Parser Version */
            parser_version: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Status */
            status: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebhookDeliveryReplayOut
         * @description Response item for POST /api/v1/webhooks/dlq/{delivery_id}/replay.
         *
         *     `restart` indicates whether the replay was queued vs already
         *     scheduled for retry (idempotent on concurrent calls). When
         *     `restart=True`, ``next_attempt_at`` echoes the freshly
         *     computed schedule time.
         */
        WebhookDeliveryReplayOut: {
            /** Attempt */
            attempt: number;
            /** Delivery Id */
            delivery_id: string;
            /**
             * Next Attempt At
             * Format: date-time
             */
            next_attempt_at: string;
            /** Restart */
            restart: boolean;
            /** Subscription Id */
            subscription_id: string;
            /** Upload Id */
            upload_id: string;
        };
        /**
         * WebhookSubscriptionCreate
         * @description POST /api/v1/webhooks request body (v0.9.0 backend).
         *
         *     The integrator does NOT supply a ``secret`` on create -- the
         *     gateway generates a fresh ``whsec_<base64(32bytes)>`` and
         *     returns it ONCE in the 201 response (see
         *     :class:`WebhookSubscriptionCreatedOut`).
         *
         *     The ``url`` field is validated as HTTPS-or-localhost per
         *     design doc §7.3 (HTTPS-only with a single explicit exception
         *     for localhost development). The route layer enforces this
         *     via the private ``_validate_webhook_url`` helper; this
         *     schema is the structural wire contract only.
         *
         *     The ``filter`` field is ``dict[str, object]`` (matches the
         *     JSONB column on ``webhook_subscriptions``). The integrator
         *     pins a subset of keys today (``upload_status``,
         *     ``fight_result``); v0.9.1 will add a ``field_validator`` to
         *     enforce string-valued filters if the spec decides to lock
         *     the contract.
         */
        WebhookSubscriptionCreate: {
            /** Description */
            description?: string | null;
            /** Filter */
            filter: {
                [key: string]: unknown;
            };
            /** Url */
            url: string;
        };
        /**
         * WebhookSubscriptionCreatedOut
         * @description Response from POST /api/v1/webhooks (v0.9.0 backend).
         *
         *     Returned ONCE -- the integrator must capture ``secret`` NOW
         *     and store it securely; it's never returned again. The
         *     ``id`` field is the ``wh_<uuid>`` discriminator that the
         *     integrator uses to identify the subscription on subsequent
         *     ``GET`` and ``DELETE`` calls.
         */
        WebhookSubscriptionCreatedOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Filter */
            filter: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Secret */
            secret: string;
            /** Url */
            url: string;
        };
        /**
         * WebhookSubscriptionOut
         * @description Response item from GET /api/v1/webhooks (v0.9.0 backend).
         *
         *     Strict subset of :class:`WebhookSubscriptionCreatedOut` --
         *     excludes the ``secret`` field (one-time only on POST per
         *     design doc §3.2). Excludes ``revoked_at`` too: per design
         *     doc §4, revoked subscriptions return 404 from public view
         *     (so listing them at all would leak existence). An
         *     auditor-side panel that surfaces revoked subscriptions
         *     with their revocation timestamp is a v0.9.1 followup
         *     (``GET /api/v1/webhooks?include_revoked=true``).
         */
        WebhookSubscriptionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Filter */
            filter: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Url */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_account_enriched_api_v1_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEnrichedOut"];
                };
            };
        };
    };
    list_fights_api_v1_fights_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FightOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fight_api_v1_fights__fight_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fight_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FightOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fight_events_api_v1_fights__fight_id__events_get: {
        parameters: {
            query?: {
                /** @description Time-bucket size for the roll-up window. Defaults to 5 seconds; bounded 1 <= window_s <= 600 (10 minutes). */
                window_s?: number;
            };
            header?: never;
            path: {
                fight_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FightEventsSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fight_skills_api_v1_fights__fight_id__skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fight_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FightSkillsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fight_squads_api_v1_fights__fight_id__squads_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fight_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FightSquadsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fight_timeline_api_v1_fights__fight_id__timeline_get: {
        parameters: {
            query?: {
                /** @description Time-bucket size for the per-fight timeline roll-up. Defaults to 5 seconds; bounded 1 <= window_s <= 600 (10 minutes). */
                window_s?: number;
            };
            header?: never;
            path: {
                fight_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerFightTimelineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_summary_api_v1_health_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryDrift"];
                };
            };
        };
    };
    list_players_api_v1_players_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filter to players whose modal profession matches the enum name (e.g. ?profession=MESMER) or integer value (e.g. ?profession=7). Default (empty / no param) returns all players. */
                profession?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerListRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_api_v1_players__account_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_timeline_api_v1_players__account_name__timeline_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                bucket?: "fight" | "day";
                tz?: string;
            };
            header?: never;
            path: {
                account_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerTimelineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_api_v1_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_upload_api_v1_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_api_v1_uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_webhooks_api_v1_webhooks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscriptionOut"][];
                };
            };
        };
    };
    create_webhook_api_v1_webhooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookSubscriptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscriptionCreatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_dlq_delivery_api_v1_webhooks_dlq__delivery_id__replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delivery_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookDeliveryReplayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_webhook_api_v1_webhooks__subscription_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_webhook_api_v1_webhooks__subscription_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
