SaveAtOut=false
OutLocation=/Users/arthurdacquet/Projects/GW2 Parser/.tooling/ei-out
SaveOutHTML=false
SaveOutCSV=false
SaveOutJSON=true
IndentJSON=false
SingleThreaded=true
ParsePhases=true
ParseCombatReplay=false
ParseExtensions=true
ComputeDamage=true
ComputeBuff=true
ComputeCast=true
ComputeMechanics=true
ComputeDamageModifiers=true
UploadToDPSReports=false
UploadToWingman=false
UploadToMistWarrior=false
UploadToRaidar=false
SkipFailedTries=false
AutoAdd=false
AutoParse=false
CompressRaw=false
ParseMultipleLogs=false
RawTimelineArrays=true
SaveOutTrace=false
ApplicationTraces=false
DetailledWvW=true
