"""Persist player dodge, block and interrupt counters in summaries.

Column lifecycle this migration has to live with (verified against a real
PostgreSQL, see ``docs/validation/migration-round-trip.md``):

1. ``0017_player_defense_events`` adds ``blocked``, ``dodges``, ``interrupts``
   to ``fight_player_summaries``.
2. ``8b674a6a9cfc_phase3_schema_changes`` -- an autogenerated migration whose
   model snapshot was behind the live schema -- **drops all three again**
   (along with ``downs``, ``deaths``, ``stun_breaks``, ``damage_taken``,
   ``fight_agents.position_samples`` and ``fights.context``).
3. So the revision this migration revises (``ea3023c87c0f``) has **none** of
   the three columns.

The product code (ORM, API schema and frontend) names the block counter
``blocks``. This migration therefore re-adds the trio under the product's
names. The ``blocked`` -> ``blocks`` rename branch is defensive only: it can
only fire on a database that never ran ``8b674a6a9cfc``, which the linear
chain makes unreachable. It is kept because it is harmless and preserves rows
if such a database exists.

Revision ID: 0022
Revises: ea3023c87c0f
Create Date: 2026-10-10
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = "0022"
down_revision: str | None = "ea3023c87c0f"
branch_labels: str | None = None
depends_on: str | None = None

_TABLE = "fight_player_summaries"

#: Columns this migration is responsible for at head.
_COUNTERS = ("blocks", "dodges", "interrupts")


def _columns() -> set[str]:
    bind = op.get_bind()
    return {column["name"] for column in sa.inspect(bind).get_columns(_TABLE)}


def upgrade() -> None:
    columns = _columns()
    if "blocks" not in columns:
        if "blocked" in columns:
            # Only reachable on a database that skipped 8b674a6a9cfc; rename
            # in place so its rows survive.
            op.alter_column(_TABLE, "blocked", new_column_name="blocks")
        else:
            op.add_column(_TABLE, sa.Column("blocks", sa.Integer(), nullable=True))
    for name in ("dodges", "interrupts"):
        if name not in columns:
            op.add_column(_TABLE, sa.Column(name, sa.Integer(), nullable=True))


def downgrade() -> None:
    """Drop the counters this migration introduces.

    The revision below (``ea3023c87c0f``) has none of them -- 8b674a6a9cfc
    removed what 0017 had added -- so dropping is the faithful inverse of
    :func:`upgrade` on the only reachable path. An earlier revision of this
    migration renamed ``blocks`` back to ``blocked`` instead, which left three
    columns the target revision does not have and made ``downgrade -1``
    untruthful.
    """
    columns = _columns()
    for name in _COUNTERS:
        if name in columns:
            op.drop_column(_TABLE, name)
