"""phase3_schema_changes

Revision ID: 8b674a6a9cfc
Revises: 57a3c9ee1b2f
Create Date: 2026-07-24 03:53:57.624392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b674a6a9cfc'
down_revision: Union[str, Sequence[str], None] = '57a3c9ee1b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fight_player_boons',
    sa.Column('fight_id', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=False),
    sa.Column('boon_name', sa.String(length=30), nullable=False, comment="Boon identifier: 'might', 'fury', 'quickness', 'alacrity', etc."),
    sa.Column('uptime', sa.Float(), nullable=True, comment='Uptime fraction [0.0-1.0]'),
    sa.Column('outgoing', sa.BigInteger(), nullable=True, comment='Total outgoing boon applications'),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fight_id', 'account_name', 'boon_name')
    )
    op.add_column('fight_agents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fight_agents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('fight_agents', 'agent_id',
               existing_type=sa.NUMERIC(precision=20, scale=0),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_index('ix_fight_agents_account_fight', 'fight_agents', ['account_name', 'fight_id'], unique=False)
    op.drop_column('fight_agents', 'position_samples')
    op.drop_column('fight_player_summaries', 'deaths')
    op.drop_column('fight_player_summaries', 'stun_breaks')
    op.drop_column('fight_player_summaries', 'interrupts')
    op.drop_column('fight_player_summaries', 'downs')
    op.drop_column('fight_player_summaries', 'dodges')
    op.drop_column('fight_player_summaries', 'damage_taken')
    op.drop_column('fight_player_summaries', 'blocked')
    op.add_column('fight_skills', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fight_skills', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fights', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fights', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('fights', 'context')
    op.drop_constraint(op.f('uq_guild_member'), 'guild_members', type_='unique')
    op.create_index('ix_guild_members_account', 'guild_members', ['account_name'], unique=False)
    op.alter_column('uploads', 'size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_index('ix_webhook_deliveries_sub_next', 'webhook_deliveries', ['subscription_id', 'next_attempt_at'], unique=False)
    op.create_foreign_key('webhook_dlq_subscription_id_fkey', 'webhook_dlq', 'webhook_subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('webhook_dlq_subscription_id_fkey', 'webhook_dlq', type_='foreignkey')
    op.drop_index('ix_webhook_deliveries_sub_next', table_name='webhook_deliveries')
    op.alter_column('uploads', 'size_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index('ix_guild_members_account', table_name='guild_members')
    op.create_unique_constraint(op.f('uq_guild_member'), 'guild_members', ['guild_id', 'account_name'], postgresql_nulls_not_distinct=False)
    op.add_column('fights', sa.Column('context', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('fights', 'updated_at')
    op.drop_column('fights', 'created_at')
    op.drop_column('fight_skills', 'updated_at')
    op.drop_column('fight_skills', 'created_at')
    op.add_column('fight_player_summaries', sa.Column('blocked', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight_player_summaries', sa.Column('damage_taken', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('fight_player_summaries', sa.Column('dodges', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight_player_summaries', sa.Column('downs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight_player_summaries', sa.Column('interrupts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight_player_summaries', sa.Column('stun_breaks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight_player_summaries', sa.Column('deaths', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fight_agents', sa.Column('position_samples', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('ix_fight_agents_account_fight', table_name='fight_agents')
    op.alter_column('fight_agents', 'agent_id',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=20, scale=0),
               existing_nullable=False)
    op.drop_column('fight_agents', 'updated_at')
    op.drop_column('fight_agents', 'created_at')
    op.drop_table('fight_player_boons')
    # ### end Alembic commands ###
