"""revert_agent_id_to_numeric

Revision ID: ea3023c87c0f
Revises: 8b674a6a9cfc
Create Date: 2026-07-24 04:06:43.898212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3023c87c0f'
down_revision: Union[str, Sequence[str], None] = '8b674a6a9cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fight_agents', 'agent_id',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fight_agents', 'agent_id',
               existing_type=sa.Numeric(precision=20, scale=0),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
